задание 8. при запуске указать row, cols, iterations
Anastasia-Papchenko/tspp_2024_papchenko pull request #10
Opened 2024-11-23 20:57 UTC by Anastasia-Papchenko

2024-11-26 07:56 UTC, Anastasia-Papchenko commented
Здравствуйте!
Можете пожалуйста сказать какие замечания есть по работе, чтобы я успела переделать к следующему семинару

2024-11-26 08:57 UTC, dimlichmanov commented
Ой, что-то я забыл вас фиолетовым отметить, извините. 
Могли и вчера сдать уже.
Я проверю чуть позже, скажу замечания если будут, но вы всё равно сдайте очно в следующий раз.

2024-11-27 11:25 UTC, dimlichmanov requested changes
Переделайте замечание, в понедельник покажете, как исправили. Отчёт ок

2024-11-27 11:25 UTC, dimlichmanov commented on game.c
> +                int ni = (x + i + rows) % rows;
А как вы считаете соседей у клетки, у которой сосед находится на другом процессе? Нужно сначала обменяться граничными условиями. И сделать это с неблокирующими операциями

2024-12-04 22:45 UTC, closed without merging