У меня к сожалению не получается реализовать данное задание. Пожалуйс…
Anastasia-Papchenko/tspp_2024_papchenko pull request #5
Opened 2024-10-05 20:22 UTC by Anastasia-Papchenko

…та подскажите на каком этапе я пишу фигню.. Терминал ругается на версию, которую я указала в объявление библиотеки, на papi_start, papi_stop и values

2024-10-05 20:28 UTC, dimlichmanov commented
Пришлите полный вывод, что говорится в терминале, пожалуйста. Можно текстом, можно скрином

2024-10-05 20:31 UTC, Anastasia-Papchenko commented
[image: image.png]

сб, 5 окт. 2024 г. в 23:28, Dmitry Lichmanov ***@***.***>:

> Пришлите полный вывод, что говорится в терминале, пожалуйста. Можно
> текстом, можно скрином
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Anastasia-Papchenko/tspp_2024_papchenko/pull/5#issuecomment-2395185353>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVNORZBHBXNXTWAOFJAAENTZ2BDYVAVCNFSM6AAAAABPNUIXFKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOJVGE4DKMZVGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-05 20:32 UTC, Anastasia-Papchenko commented
error: too many decimal points in number
   61 |     int PAPI_library_init(int 6.0.0.0);
      |                               ^~~~~~~
Graph_csr.c:61:31: error: expected ‘;’, ‘,’ or ‘)’ before numeric constant
Graph_csr.c:70:27: warning: passing argument 1 of ‘PAPI_start’ makes
integer from pointer without a cast [-Wint-conversion]
   70 |     if (PAPI_start((int[]){PAPI_L1_TCM, PAPI_L2_TCM}, 2) !=
PAPI_OK) {
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                           |
      |                           int *
In file included from Graph_csr.c:3:
/usr/include/papi.h:1091:25: note: expected ‘int’ but argument is of type
‘int *’
 1091 |    int   PAPI_start(int EventSet); /**< start counting hardware
events in an event set */
      |                     ~~~~^~~~~~~~
Graph_csr.c:70:9: error: too many arguments to function ‘PAPI_start’
   70 |     if (PAPI_start((int[]){PAPI_L1_TCM, PAPI_L2_TCM}, 2) !=
PAPI_OK) {
      |         ^~~~~~~~~~
In file included from Graph_csr.c:3:
/usr/include/papi.h:1091:10: note: declared here
 1091 |    int   PAPI_start(int EventSet); /**< start counting hardware
events in an event set */
      |          ^~~~~~~~~~
Graph_csr.c:89:15: warning: passing argument 1 of ‘PAPI_stop’ makes integer
from pointer without a cast [-Wint-conversion]
   89 |     PAPI_stop(values, 2);
      |               ^~~~~~
      |               |
      |               long long int *
In file included from Graph_csr.c:3:
/usr/include/papi.h:1093:24: note: expected ‘int’ but argument is of type
‘long long int *’
 1093 |    int   PAPI_stop(int EventSet, long long * values); /**< stop
counting hardware events in an event set and return current events */
      |                    ~~~~^~~~~~~~
Graph_csr.c:89:23: warning: passing argument 2 of ‘PAPI_stop’ makes pointer
from integer without a cast [-Wint-conversion]
   89 |     PAPI_stop(values, 2);
      |                       ^
      |                       |
      |                       int
In file included from Graph_csr.c:3:
/usr/include/papi.h:1093:46: note: expected ‘long long int *’ but argument
is of type ‘int’
 1093 |    int   PAPI_stop(int EventSet, long long * values); /**< stop
counting hardware events in an event set and return current events */

сб, 5 окт. 2024 г. в 23:28, Dmitry Lichmanov ***@***.***>:

> Пришлите полный вывод, что говорится в терминале, пожалуйста. Можно
> текстом, можно скрином
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Anastasia-Papchenko/tspp_2024_papchenko/pull/5#issuecomment-2395185353>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVNORZBHBXNXTWAOFJAAENTZ2BDYVAVCNFSM6AAAAABPNUIXFKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOJVGE4DKMZVGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-05 20:43 UTC, dimlichmanov commented
вы принципиально не пользуетесь моим шаблоном test_wrapper.cpp?)

2024-10-05 20:46 UTC, Anastasia-Papchenko commented
Поняла
Мой косяк, в этот раз плохо просмотрела код в репозитории

Сб, 5 окт. 2024 г. в 23:43, Dmitry Lichmanov ***@***.***>:

> вы принципиально не пользуетесь моим шаблоном test_wrapper.cpp?)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Anastasia-Papchenko/tspp_2024_papchenko/pull/5#issuecomment-2395192572>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVNORZENZJF5JO7PXA3VCUDZ2BFQDAVCNFSM6AAAAABPNUIXFKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOJVGE4TENJXGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-07 20:53 UTC, Anastasia-Papchenko commented
Можете пожалуйста как будет возможность отправить мне замечание, которое было по коду, чтобы я переделала

2024-10-07 21:27 UTC, dimlichmanov commented
Всё хорошо, кроме
1) я не вижу первого алгоритма. Нужно было сравнить показатели событий на нём, на втором алгоритме, и сделать маленький вывод.
2) Если у вас не собирается PAPI_L2_TCM, замените его на  PAPI_L2_DCM, если нет и его, выберите что-нибудь из доступных, близкое по смыслу
3) Третьим событием соберите native event(отличное от PAPI_...), примерно как в моём примере в sem03/papi_array_native.c

Не спешите особо, в зелёный дедлайн вы и так уложились.

2024-10-07 21:27 UTC, dimlichmanov requested changes

2024-10-07 21:27 UTC, dimlichmanov commented on Graph_csr.c
> +    int PAPI_library_init(int 6.0.0.0);
нужно писать  PAPI_library_init(PAPI_VER_CURRENT); (ну и проверить что функция вернула PAPI_OK, то есть 0)
у вас в papi.h объявлены версии 
#define PAPI_VERSION  			PAPI_VERSION_NUMBER(7,2,0,0)
#define PAPI_VER_CURRENT 		(PAPI_VERSION & 0xffff0000)
Весь перевод из 4-циферного кода в int делается за вас.

2024-10-07 21:27 UTC, dimlichmanov commented on Graph_csr.c
> +    if (PAPI_start((int[]){PAPI_L1_TCM, PAPI_L2_TCM}, 2) != PAPI_OK) {
Так, вы совсем забыли про EventSet. Сначала нужно его создать, затем туда добавить события, и только потом начинать считать. и PAPI_Start, и PAPI_stop работают с EventSet

2024-10-07 21:27 UTC, dimlichmanov commented on Graph_csr.c
> +    if (PAPI_start((int[]){PAPI_L1_TCM, PAPI_L2_TCM}, 2) != PAPI_OK) {
Посмотрите в моём репозитории пример sem03/papi_list.c

2024-10-07 21:27 UTC, dimlichmanov commented on Graph_csr.c
> +    PAPI_stop(values, 2);
Здесь первый параметр - EventSet, а второй как раз будет values

2024-10-12 16:27 UTC, dimlichmanov commented
На почту отправил, вроде у меня что-то считает.
Из основного - делать add_event в cout не нужно, это сбивает настройки по values (вы их вообще объявили [2])
Напутали с event_set и event_code в самом начале.

2024-10-12 18:25 UTC, Anastasia-Papchenko commented
Вот вывод программы у меня, кода который вы отправили на почту: Количество вершин = 4096, Количество ребер = 131072
Will be succeeded in measuring -2147483598 event L2 Cache event not available.
PAPI_add_event error !
n-2147483598, PAPI_TOT_INS, count: Instr completed
     Название теста: synt, Алгоритм 1 - Индекс вершины с наибольшим рангом: 447, Кэш-промах L1: 0, Кэш-промах L2: 0
values[2] = 0
Тест: synt, Алгоритм 2 - Индекс вершины с наибольшим рангом: 1760, Кэш-промах L1: 0, Кэш-промах L2: 0
values[2] = 0
Количество вершин = 1379918, Количество ребер = 1921656
Will be succeeded in measuring -2147483598 event L2 Cache event not available.
PAPI_add_event error !
n-2147483598, PAPI_TOT_INS, count: Instr completed
     Название теста: road_graph, Алгоритм 1 - Индекс вершины с наибольшим рангом: 474251, Кэш-промах L1: 0, Кэш-промах L2: 0
values[2] = 0
Тест: road_graph, Алгоритм 2 - Индекс вершины с наибольшим рангом: 474251, Кэш-промах L1: 0, Кэш-промах L2: 0
values[2] = 0
Количество вершин = 281904, Количество ребер = 2312493
Will be succeeded in measuring -2147483598 event L2 Cache event not available.
PAPI_add_event error !
n-2147483598, PAPI_TOT_INS, count: Instr completed
     Название теста: stanford, Алгоритм 1 - Индекс вершины с наибольшим рангом: 48966, Кэш-промах L1: 0, Кэш-промах L2: 0
values[2] = 0
Тест: stanford, Алгоритм 2 - Индекс вершины с наибольшим рангом: 8947, Кэш-промах L1: 0, Кэш-промах L2: 0
values[2] = 0
Количество вершин = 1134891, Количество ребер = 2987620
Will be succeeded in measuring -2147483598 event L2 Cache event not available.
PAPI_add_event error !
n-2147483598, PAPI_TOT_INS, count: Instr completed
     Название теста: youtube, Алгоритм 1 - Индекс вершины с наибольшим рангом: 41, Кэш-промах L1: 0, Кэш-промах L2: 0
values[2] = 0
Тест: youtube, Алгоритм 2 - Индекс вершины с наибольшим рангом: 382, Кэш-промах L1: 0, Кэш-промах L2: 0
values[2] = 0
Количество вершин = 32768, Количество ребер = 1048576
Will be succeeded in measuring -2147483598 event L2 Cache event not available.
PAPI_add_event error !
n-2147483598, PAPI_TOT_INS, count: Instr completed
     Название теста: syn_rmat, Алгоритм 1 - Индекс вершины с наибольшим рангом: 6931, Кэш-промах L1: 0, Кэш-промах L2: 0
values[2] = 0
Тест: syn_rmat, Алгоритм 2 - Индекс вершины с наибольшим рангом: 20486, Кэш-промах L1: 0, Кэш-промах L2: 0
values[2] = 0

2024-10-12 18:26 UTC, Anastasia-Papchenko commented
Может ли как то влиять версия papi, которая установлена глобально (6.0.0.0), на то, что я обращаюсь к версии papi 7-2, которую установила с репозитория?

2024-10-12 18:28 UTC, Anastasia-Papchenko commented
Собираю код так: 
c++ Graph_csr_new.cpp -lpapi -o Graph_new -I/study/papi/src -L/study/papi/src

2024-10-12 18:28 UTC, dimlichmanov commented
Вы собираете с флагами -I -L?

2024-10-12 18:32 UTC, dimlichmanov commented
А если собрать всё с глобальной papi, становится лучше?

2024-10-12 18:36 UTC, Anastasia-Papchenko commented
нет, остается так же

2024-10-12 18:38 UTC, dimlichmanov commented
Ладно, давайте на семинаре разберёмся.

2024-12-23 20:40 UTC, Anastasia-Papchenko commented
Пожалуйста, избавьте меня от этого проклятья третьего задания...
Я не знаю, что происходит, почему все ломается

c++ Graph_csr.cpp -lpapi -o Graph_csr -I/home/nastya/study/papi/src -L/home/nastya/study/papi/src
nastya@LAPTOP-S30HMKRR:~/study/tspp_2024_papchenko$ ./Graph_csr
Количество вершин = 4096, Количество ребер = 131072
Название теста: synt
Алгоритм 1 - Индекс вершины с наибольшим рангом: 448
Кэш-промах L1: 140157985607264, Кэш-промах L2: 140157985606368, PERF_COUNT_HW_CACHE_REFERENCES: 140157985606048
Алгоритм 2 - Индекс вершины с наибольшим рангом: 448
Кэш-промах L1: 140157985607264, Кэш-промах L2: 140157985606368, PERF_COUNT_HW_CACHE_REFERENCES: 140157985606048

Количество вершин = 1379918, Количество ребер = 1921656
Название теста: road_graph
Алгоритм 1 - Индекс вершины с наибольшим рангом: 474252
Кэш-промах L1: 140157985607264, Кэш-промах L2: 140157985606368, PERF_COUNT_HW_CACHE_REFERENCES: 140157985606048
Алгоритм 2 - Индекс вершины с наибольшим рангом: 474251
Кэш-промах L1: 140157985607264, Кэш-промах L2: 140157985606368, PERF_COUNT_HW_CACHE_REFERENCES: 140157985606048

Количество вершин = 281904, Количество ребер = 2312493
Название теста: stanford
Алгоритм 1 - Индекс вершины с наибольшим рангом: 28227
Кэш-промах L1: 140157985607264, Кэш-промах L2: 140157985606368, PERF_COUNT_HW_CACHE_REFERENCES: 140157985606048
Алгоритм 2 - Индекс вершины с наибольшим рангом: 48967
Кэш-промах L1: 140157985607264, Кэш-промах L2: 140157985606368, PERF_COUNT_HW_CACHE_REFERENCES: 140157985606048

Количество вершин = 1134891, Количество ребер = 2987620
Название теста: youtube
Алгоритм 1 - Индекс вершины с наибольшим рангом: 383
Кэш-промах L1: 140157985607264, Кэш-промах L2: 140157985606368, PERF_COUNT_HW_CACHE_REFERENCES: 140157985606048
Алгоритм 2 - Индекс вершины с наибольшим рангом: 321
Кэш-промах L1: 140157985607264, Кэш-промах L2: 140157985606368, PERF_COUNT_HW_CACHE_REFERENCES: 140157985606048

Количество вершин = 32768, Количество ребер = 1048576
Название теста: syn_rmat
Алгоритм 1 - Индекс вершины с наибольшим рангом: 20487
Кэш-промах L1: 140157985607264, Кэш-промах L2: 140157985606368, PERF_COUNT_HW_CACHE_REFERENCES: 140157985606048
Алгоритм 2 - Индекс вершины с наибольшим рангом: 6932
Кэш-промах L1: 140157985607264, Кэш-промах L2: 140157985606368, PERF_COUNT_HW_CACHE_REFERENCES: 140157985606048

2024-12-25 11:55 UTC, dimlichmanov commented
![изображение](https://github.com/user-attachments/assets/efed56ce-94e9-47e3-a597-9b879024ecb7)

2024-12-25 11:59 UTC, dimlichmanov commented
я вместо PAPI_L2_TCM взял PAPI_L2_DCM, ну и для L1 аналогично.
в papi_avail TCM недоступны.
Попробуйте.

2024-12-26 00:51 UTC, Anastasia-Papchenko commented
Все работает!! Наконец-то!!

The output (if any) follows:

Количество вершин = 4096, Количество ребер = 131072
Название теста: synt
Алгоритм 1 - Индекс вершины с наибольшим рангом: 448
Кэш-промах L1: 8928, Кэш-промах L2: 168, PERF_COUNT_HW_CACHE_REFERENCES: 3888164
Алгоритм 2 - Индекс вершины с наибольшим рангом: 448
Кэш-промах L1: 2802633, Кэш-промах L2: 159278, PERF_COUNT_HW_CACHE_REFERENCES: 2880825345
Количество вершин = 1379918, Количество ребер = 1921656
Название теста: road_graph
Алгоритм 1 - Индекс вершины с наибольшим рангом: 474252
Кэш-промах L1: 220035, Кэш-промах L2: 648, PERF_COUNT_HW_CACHE_REFERENCES: 101117219
Алгоритм 2 - Индекс вершины с наибольшим рангом: 474251
Кэш-промах L1: 490447, Кэш-промах L2: 104651, PERF_COUNT_HW_CACHE_REFERENCES: 284851489
Количество вершин = 281904, Количество ребер = 2312493
Название теста: stanford
Алгоритм 1 - Индекс вершины с наибольшим рангом: 28227
Кэш-промах L1: 221850, Кэш-промах L2: 893, PERF_COUNT_HW_CACHE_REFERENCES: 71536043
Алгоритм 2 - Индекс вершины с наибольшим рангом: 48967
Кэш-промах L1: 2043669, Кэш-промах L2: 524643, PERF_COUNT_HW_CACHE_REFERENCES: 2320975155
Количество вершин = 1134891, Количество ребер = 2987620
Название теста: youtube
Алгоритм 1 - Индекс вершины с наибольшим рангом: 383
Кэш-промах L1: 320438, Кэш-промах L2: 848, PERF_COUNT_HW_CACHE_REFERENCES: 112083504
Алгоритм 2 - Индекс вершины с наибольшим рангом: 321
Кэш-промах L1: 13272634, Кэш-промах L2: 3056491, PERF_COUNT_HW_CACHE_REFERENCES: 5626565679
Количество вершин = 32768, Количество ребер = 1048576
Название теста: syn_rmat
Алгоритм 1 - Индекс вершины с наибольшим рангом: 20487
Кэш-промах L1: 96439, Кэш-промах L2: 124, PERF_COUNT_HW_CACHE_REFERENCES: 30723396
Алгоритм 2 - Индекс вершины с наибольшим рангом: 6932
Кэш-промах L1: 53686942, Кэш-промах L2: 2997296, PERF_COUNT_HW_CACHE_REFERENCES: 46788047401

2024-12-26 08:06 UTC, dimlichmanov approved these changes

2024-12-26 08:12 UTC, closed without merging