я пытаюсь распараллелить программу с помощью pragma, но при увеличени…
Anastasia-Papchenko/tspp_2024_papchenko pull request #7
Opened 2024-10-25 17:15 UTC by Anastasia-Papchenko

…и числа потоков время работы программы у меня тоже увеличивается. может на это как-то влияют #pragma omp atomic? подскажите пожалуйста

2024-10-25 22:11 UTC, dimlichmanov requested changes
Вспомните, что я говорил про rand(). 
Надо как-то сделать, чтобы генерация значений внутри каждого потока была независимой

2024-10-26 10:32 UTC, dimlichmanov commented
А вы усредняете показатели (по 3-4 запускам) хотя бы? Чтобы амортизировать подобные скачки.

2024-10-26 11:01 UTC, Anastasia-Papchenko commented
Видимо нет… потому что я не поняла что вы имеете ввиду…

Сб, 26 окт. 2024 г. в 13:32, Dmitry Lichmanov ***@***.***>:

> А вы усредняете показатели (по 3-4 запускам) хотя бы? Чтобы амортизировать
> подобные скачки.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Anastasia-Papchenko/tspp_2024_papchenko/pull/7#issuecomment-2439483077>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVNORZHMTQRBFU3I6L25FPDZ5NVUVAVCNFSM6AAAAABQTWJZEWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMZZGQ4DGMBXG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-26 11:45 UTC, dimlichmanov commented
Вас смущает, что у вас эффективность и ускорение при N = 70000 выше, чем при соседних показателях N. Это повторяется с каждым запуском, или это разовый выброс? Посмотрите. В целом ничего критического даже в том, что это выброс, нет.

2024-10-26 14:15 UTC, Anastasia-Papchenko commented
Сейчас несколько раз еще запустила программу. Да, такой скачок раз через раз бывает, видимо все нормально

2024-10-26 14:44 UTC, dimlichmanov commented on wandering.c
> +        unsigned int seed = omp_get_thread_num() + time(NULL);
Как вы думаете, seed всегда будут различны?

2024-10-26 15:57 UTC, Anastasia-Papchenko commented
Чуть чуть) ... я не знаю на что замерить rand_r()...
Thread 1 seed: 1729958009
Thread 2 seed: 1729958010
Thread 9 seed: 1729958017
Thread 10 seed: 1729958018
Thread 0 seed: 1729958008
Thread 3 seed: 1729958011
Thread 6 seed: 1729958014
Thread 8 seed: 1729958016
Thread 5 seed: 1729958013
Thread 11 seed: 1729958019
Thread 12 seed: 1729958020
Thread 7 seed: 1729958015
Thread 15 seed: 1729958023
Thread 13 seed: 1729958021
Thread 4 seed: 1729958012
Thread 14 seed: 1729958022

2024-10-26 16:19 UTC, dimlichmanov commented
нет, с rand_r вопросов нет
Посмотрите, у вас все значения лежат красиво от 1729958009 до 1729958023, то есть time() было одним и тем же, каждый поток просто прибавил свой id. Согласитесь, time() не обязан был быть равным в каждом потоке. Так что совпадение seed у разных потоков вполне вероятно. Этого нужно избежать.
Оставьте просто omp_get_thread_num(). Ну или дополнительно сделайте так, чтобы time() был обязательно одним и тем же у разных потоков - тогда вы будете уверны, что всю разницу вам сделает omp_get_thread_num

2024-10-26 16:31 UTC, dimlichmanov commented
Работает, проверили?

2024-10-26 16:34 UTC, Anastasia-Papchenko commented
теперь seed равно значению потока, который в него заходит
в остальном программа запускается

сб, 26 окт. 2024 г. в 19:32, Dmitry Lichmanov ***@***.***>:

> Работает, проверили?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Anastasia-Papchenko/tspp_2024_papchenko/pull/7#issuecomment-2439644486>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVNORZACBCZ7NC55QTL55TDZ5O7ZFAVCNFSM6AAAAABQTWJZEWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMZZGY2DINBYGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-26 16:37 UTC, dimlichmanov commented
Она запускается или работает как надо, в плане случайных блужданий?)

2024-10-26 16:42 UTC, Anastasia-Papchenko commented
Да, случайные блуждания работают. Сейчас еще раз на своем пк проверила, не на полюсе

2024-10-26 16:48 UTC, dimlichmanov approved these changes
Хорошо, засчитываю.

2024-11-03 13:23 UTC, closed without merging