отправляю первый варинт дз-6
Anastasia-Papchenko/tspp_2024_papchenko pull request #8
Opened 2024-11-02 21:16 UTC by Anastasia-Papchenko

2024-11-03 13:05 UTC, dimlichmanov requested changes
Проверьте, что полученный массив реально отсортирован.

2024-11-03 13:07 UTC, Anastasia-Papchenko commented
Я проверяла результаты на маленьких массивах, они отсортировываются
правильно

Там есть часть закоменченого кода, который как раз выводит массив конечный


Вс, 3 нояб. 2024 г. в 16:05, Dmitry Lichmanov ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Проверьте, что полученный массив реально отсортирован.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Anastasia-Papchenko/tspp_2024_papchenko/pull/8#pullrequestreview-2411851600>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVNORZEN6YIBMHXGNBFEFTTZ6YNTFAVCNFSM6AAAAABRCB66DGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMJRHA2TCNRQGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2024-11-03 13:14 UTC, dimlichmanov commented
Сделайте автоматическую проверку (a[i] <= a[i+1]) и зачту

2024-11-04 11:23 UTC, dimlichmanov approved these changes

2024-11-10 17:14 UTC, closed without merging